name: Python application

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_srv_one
          POSTGRES_PASSWORD: test_srv_one123
          POSTGRES_DB: test_service_one
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        alembic upgrade head
      env:
        PG_USER: test_srv_one
        PG_PASS: test_srv_one123
        PG_DB: test_service_one
      working-directory: ./src/service_one
    - name: Test with pytest
      working-directory: ./src/service_one
      run: |
        pytest